### ISSUE TITLE
TPS drops on radius claim and unclaim

### ISSUE THREAD

**Issue by oloflarsson** [webbukkit/Dynmap-Factions#11]
When many people radius claim or radius unclaim large areas the TPS drops to 0 for a short while. We just released a new world map on my server and due to all the claming the profiling results looks like this: http://i.imgur.com/7S3TDEO.png

Could you optimize this somehow? Perhaps reduce the ordo some way. Additionally you could possibly run the update async instead?

**Comment by oloflarsson** [comment]
I think this would be the line getting repeated to often:
https://github.com/webbukkit/Dynmap-Factions/blob/1d71852a81ef5ce9de87d138f32c3354af5d21f6/src/main/java/org/dynmap/factions/DynmapFactionsPlugin.java#L476

**Comment by oloflarsson** [comment]
bump?

**Comment by mikeprimm** [comment]
Not sure which version you're running - give http://mikeprimm.com/dynmap/builds/Dynmap-Factions/Dynmap-Factions-0.72.jar or http://mikeprimm.com/dynmap/builds/Dynmap-Factions-1.8.x/Dynmap-Factions-1.8.x-0.72.jar , as appropriate

**Comment by oloflarsson** [comment]
This is the plugin.yml

``` yaml
name: Dynmap-Factions
main: org.dynmap.factions.DynmapFactionsPlugin
version: "0.71-26"
author: mikeprimm
depend: [ dynmap, Factions ]
```
